Use absolute_import from the __future__ everywhere
Without this, among other things, we can end up with conflicts with
new upstream modules.  For example, given lib/bup/io.py:

  Traceback (most recent call last):
    File "/home/rlb/src/bup/main-4/cmd/bup-index", line 10, in <module>
      from bup import metadata, options, git, index, drecurse, hlinkdb
    File "/home/rlb/src/bup/main-4/lib/bup/metadata.py", line 10, in <module>
      from io import BytesIO
  ImportError: cannot import name BytesIO

This switch also revealed a circular dependency between midx and git,
and several places where we weren't qualifying our bup imports
properly, i.e. "import git" rather than "from bup import git".

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>