CatPipe.close: do nothing on redundant call
If the catpipe has already been closed, do nothing.

The previous arrangement could cause errors when running a single test
like this:

  ./pytest test/int/test_client.py

that looked like this:

    File "/home/rlb/src/bup/treesplit/lib/bup/main.py", line 338, in run_module_cmd
      close_catpipes()
    File "/home/rlb/src/bup/treesplit/lib/bup/git.py", line 1408, in close_catpipes
      cp.close(wait=True)
    File "/home/rlb/src/bup/treesplit/lib/bup/git.py", line 1303, in close
      p.wait()
      ^^^^^^
  AttributeError: 'NoneType' object has no attribute 'wait'

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>