test-prune-older: disable background gc
The debian buildd's exposed a race between the default automatic
background gc and the explict gc in the test, resulting in:

  git commit --date 1566025987 -qam 1566025987
  Auto packing the repository in background for optimum performance.
  See "git help gc" for manual housekeeping.
  git gc --aggressive
  fatal: gc is already running on machine 'zandonai' pid 34323 (use --force if not)
  Traceback (most recent call last):
    File "t/test-prune-older", line 190, in <module>
      save_utcs = create_older_random_saves(save_population, three_years_ago, now)
    File "t/test-prune-older", line 74, in create_older_random_saves
      exc(['git', 'gc', '--aggressive'])
    File "t/test-prune-older", line 41, in exc
      check_call(cmd, shell=shell)
    File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['git', 'gc', '--aggressive']' returned non-zero exit status 128

Fix it by disabling gc.autoDetach in the git config for the test repo
-- something we may well need to do in other tests too.

Thanks to Robert Edmonds for reporting the problem and suggesting the
fix.

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>