split: add missing import "parse_date_or_fatal"
Without this "bup split -n NAME -d STAMP FILE" produces an error:

  Traceback (most recent call last):
    File "/usr/lib/bup/cmd/bup-split", line 67, in <module>
      date = parse_date_or_fatal(opt.date, o.fatal)
  NameError: name 'parse_date_or_fatal' is not defined

Signed-off-by: Fabian 'xx4h' Melters <xx4h@xx4h.de>
[rlb@defaultvalue.org: rebase on current master; adjust commit
 message; fix commit author]
Reviewed-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>