Fix more gcc type punning errors introduced by the metadata changes.
Whatever, let's use 0 and 1 instead of Py_True and Py_False.

_helpers.c: In function ‘bup_set_linux_file_attr’:
_helpers.c:683: warning: dereferencing type-punned pointer will break
strict-aliasing rules
_helpers.c:683: warning: dereferencing type-punned pointer will break
strict-aliasing rules
_helpers.c: In function ‘bup_utimensat’:
_helpers.c:758: warning: dereferencing type-punned pointer will break
strict-aliasing rules
_helpers.c:758: warning: dereferencing type-punned pointer will break
strict-aliasing rules
_helpers.c: In function ‘init_helpers’:
_helpers.c:940: warning: dereferencing type-punned pointer will break
strict-aliasing rules
_helpers.c:941: warning: dereferencing type-punned pointer will break
strict-aliasing rules
error: command 'gcc' failed with exit status 1

Signed-off-by: Avery Pennarun <apenwarr@gmail.com>