vfs: rely on FakeLink's target in readlink
This could result in an error like:

  File "/usr/local/lib/bup/bup/vfs.py", line 524, in _compute_item_size
    return len(_readlink(repo, item.oid))
  AttributeError: 'FakeLink' object has no attribute 'oid'

Thanks to Hartmut Krafft for reporting the problem and helping devise
the solution.

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
(cherry picked from commit 023917c97cbf9bf6dbfad7120b41850dc5d7c7cd)
Tested-by: Rob Browning <rlb@defaultvalue.org>