establish_default_repo: report non-dir top; drop stat_if_exists
Previously if the repository path wasn't directory, we would claim
that it didn't exist.

  error: repository b'/home/rlb/.bup/' does not exist (see "bup help init")

Now that's:

  error: /home/rlb/.bup/ is not a repository

Since establish_default_repo is the only caller, and since the
addition of FileNotFoundError and NotADirectoryError has made its work
easy, remove stat_if_exists.

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>